### ISSUE TITLE
Add and option to name class files with lowercase

### ISSUE THREAD

**Issue by bodyo** [tzAcee/cpp-class-creator#13]
Your extension is great, Thank you!!

I would like to have one more option in settings:
When I create class I would like to have the option `"cpp.creator.fileName.lowercase": = boolean : [FALSE] by default`
This option creates class's files with lowercase
For example
I create class JsonParser
your tool create two files
```
jsonparser.cpp
jsonparser.hpp
```

with content:
```
class JsonParser  
{
	private:

	public:

		JsonParser();
		~JsonParser();

};
```

**Comment by fleexo** [comment]
I'll take my hands on that! Sorry for the late response, was pretty busy with university stuff 💯

**Comment by fleexo** [comment]
With the flexible presets you can achieve that now!

**Comment by bodyo** [comment]
> With the flexible presets you can achieve that now!

thank you!!
