### ISSUE TITLE
Auto Add file header to new files

### ISSUE THREAD

**Issue by saurabheights** [tzAcee/cpp-class-creator#14]
VS Code has support for adding file header, for example typing "/**" and pressing enter auto-completes the file header.

/**
 * @file abc.hpp
 * @author Saurabh Khanduja (abc@gmail.com)
 * @brief abc
 * @version 0.1
 * @date 05.11.2021
 * 
 * Copyright (C) abc - All Rights Reserved
 */
I believe its done using doxygen, customizable in settings.
When creating a class using your extension, it would be great if there is an option to auto add the file header.

**Comment by fleexo** [comment]
With the new preset you can do it now.

Just add the file header in the presets and make sure to use the right command on @file -> @file {{\*HEADERFILENAME or SOURCEFILENAME\*}.
