### ISSUE TITLE
Selecting path to a nested folder

### ISSUE THREAD

**Issue by giammi56** [tzAcee/cpp-class-creator#15]
I have some troubles selecting the path of the new class. The .cpp file I am focussed on the editor is in the relative path `/relative/path/folder/project`. Modifying the setting.json _of the whole VScode_ on Ubuntu 20.04:

`"cpp.creator.setPath": "."` creates the .cpp and .h file in `/home/myusrname`;
`"cpp.creator.setPath": "/relative/path/folder/project"` says the folder doesn't exist;
`"cpp.creator.setPath": "${fileDirname}` creates a new folder in `/home`.

I have multiple projects open into the same workspace, each in his own folder. The best would be to use a reference (e.g. `${fileDirname}`) to the folder of the current .cpp file. Any idea?

**Comment by AndersHogqvist** [comment]
I have this issue as well! It would be nice if there was an option to create the files in the same folder as the file I'm currently editing or in the folder that you right click on in the project tree.

**Comment by AndersHogqvist** [comment]
I found the problem, fixed it and made a pull request: https://github.com/tzAcee/cpp-class-creator/pull/20

**Comment by fleexo** [comment]
Thanks for your fix. Merged #20
