### ISSUE TITLE
have an option to create implementation file with .cc instead of .cpp

### ISSUE THREAD

**Issue by AnloWho** [tzAcee/cpp-class-creator#19]
I've been using this plugin for some while now. However, the code base I'm working on uses .cc instead of .cpp for the implementation files. It would also be nice to be able to switch whether you want  the private: directive before or after the public: one.
I also would like to use spaces as indents, rather than tabs in the newely created files. And guess what I have a pull request pending for all this :)

**Comment by fleexo** [comment]
Merged your PR #18
