### ISSUE TITLE
Documentation is misleading regarding placement of generated class & other weirdness

### ISSUE THREAD

**Issue by madsdyd** [tzAcee/cpp-class-creator#2]
Hi Maxim

From the documentation you would get the impression that any configuration file would work, for configuring the output dir. But, actually, only a setting from the workplace is read. I believe this should be clear from the documentation, or you should read the configuration in a manner that matches the model for configuration in vscode.

Additionally, I have a hard time finding out how the code would ever work besides the default model of creating a directory based on the class name (it surely does not work for me, if I provide a directory where I want the files to go). The create_class method, only accepts a non-existing directory...:

```ts
if (fs.existsSync(dir)) {
		var stats = fs.lstatSync(dir);

		if (stats.isDirectory()) {
			return false; <<< What?
		}
	}
	fs.mkdirSync(dir); <<< What? 
```

Basically, it seems that this extension wants to create a directory for *every* class it creates. Clearly this is not a standard pattern? And, it requires one to update the configuration for every class one wants to create? That seems broken.

I believe you probably meant something like this:

```ts
// Check if dir already exists, if it does, it must be a directory.
if (fs.existsSync(dir)) {
		var stats = fs.lstatSync(dir);
                // Must be a directory, if not, return an error.
		if (! stats.isDirectory()) {
			return false; 
		}
} else {
        // Directory does not exist, create it.       
	fs.mkdirSync(dir);
}
```
(I don't know typescript, so syntax may be different - I assumed it works like JavaScript).

And, while we are at it: Why would you limit a class name to 12 characters? This is just plain weird to me. Tons of C++ classes have names longer than 12 characters.

**Comment by fleexo** [comment]
Hey @madsdyd 
thank you for issue :).
The simplest thing with the class name length was just increased. That was just dumb from me.
You are probably right, that I messed something up in the create_class function, while trying to add the output dir from the settings. Your solution works just fine. Thank you :). 

I also made the creation of the folder with the class optional so that it is created just as two files by standard.

The last thing is the output dir stuff. You now can just set the path as a string in the settings.json, set it to true so a input window pops up where you can set your path or just let it undefined so it will be created @ the workspace.

I will also improve the documentation :)

Thank you for your feedback I really appreciate it :D

**Comment by madsdyd** [comment]
> Hey @madsdyd
> thank you for issue :).

You are welcome, thanks for creating the plugin!

> The simplest thing with the class name length was just increased. That was just dumb from me.

Well, might be you had some intention with it. Just seemed weird ;-).

> You are probably right, that I messed something up in the create_class function, while trying to add the output dir from the settings. Your solution works just fine. Thank you :).

You are welcome.

> 
> I also made the creation of the folder with the class optional so that it is created just as two files by standard.

Sounds very reasonable!
> 
> The last thing is the output dir stuff. You now can just set the path as a string in the settings.json, set it to true so a input window pops up where you can set your path or just let it undefined so it will be created @ the workspace.

Sounds flexible (not totally clear from me, will try to test it out).
> 
> I will also improve the documentation :)

Sounds good. Good documentation attracts users. And, forces you to consider what your code does, if it matches the use cases, etc. Writing good documentation is a great habit.
> 
> Thank you for your feedback I really appreciate it :D

No problem - looking forward to test the changes. I am new to the whole vscode ecosystem - will you release a new version soon & will it autoupdate, or do I need to do something?

Thanks, 

Mads

**Comment by fleexo** [comment]
Normally it should auto-update. But you can check in the built-in vscode market whether you can install a newer version.
