### ISSUE TITLE
0.28 is not working

### ISSUE THREAD

**Issue by leecottrellPTC** [tzAcee/cpp-class-creator#22]
When I used your class creator tool version 0.28 I received this error. 
![image](https://user-images.githubusercontent.com/44240965/152211676-c5216226-131c-4203-afd0-364ed9bb40b3.png)

When I downgraded to 0.27 it worked.

I am running Windows 11 home. I am the admin and have the most recent VSC installed.

**Comment by fleexo** [comment]
Thanks! hotfixed it.
Was working on another feature, I tbh didn't meant to release 0.28 lol.
