### ISSUE TITLE
Enable date/time stamps in Header/Source Content Preset

### ISSUE THREAD

**Issue by markspacehub** [tzAcee/cpp-class-creator#27]
The header file content preset field is great and very useful. However I am required to time stamp all files I create at their creation.
Is it possible to add a command, similar to {{*CLASSNAME*}} that will print the date and/or time in the content preset?

{{*CURRENTDATE*}} - puts current date
{{*CURRENTTIME*}} - puts current time

**Comment by fleexo** [comment]
Sure, I could add something like that, as soon as I find time (prob. this weekend)

Or feel free to contribute of course 😃

**Comment by markspacehub** [comment]
I've not worked on a vs extension before - it could be interesting. I will have a look on Friday and see what I can do!

**Comment by markspacehub** [comment]
@tzAcee I've been working on the extension and I think I have added the required functionality. I have put this in a PR. I haven't worked on an extension, or in typescript or done any contributing to projects on GitHub before, so I look forward to any feedback you may have!

**Comment by fleexo** [comment]
Nice, thank you!
Looks good to me at first glance 😃 

Will handle it this weekend.

**Comment by fleexo** [comment]
Thank you again.

Extension is published with your changes.
