### ISSUE TITLE
#ifndef

### ISSUE THREAD

**Issue by Cruz965** [tzAcee/cpp-class-creator#4]
Would be cool if it already had the #ifndef ANIMAL_H  when i create a header file for the Animal class for instance.

**Comment by fleexo** [comment]
There is already #pragma once on top,
so it shouldn't be necessary to do both.

But I will add an option to do so.

**Comment by adistomar** [comment]
> There is already #pragma once on top,
> so it shouldn't be necessary to do both.
> 
> But I will add an option to do so.

I think some compilers don't recognize the #pragma once. So giving an option for the #ifndef can be helpful.

**Comment by fleexo** [comment]
@Cruz965 
@aditya2604 
I just added the settings to make ifndef & pragma once optional, so you can now use ifndef :)
