### ISSUE TITLE
configure .h or .hpp

### ISSUE THREAD

**Issue by FIorian** [tzAcee/cpp-class-creator#5]
Is it possible to configure the extension to generate either .h or .hpp files?

Edit: you probably have your reasons for doing it this way and I don't 100% know what the difference is between .h and .hpp...

**Comment by fleexo** [comment]
@FIorian .hpp are C++ Headers and .h are C header (c++ compatible ofc).
 Not a big deal. I will add a setting for that :)

**Comment by FIorian** [comment]
Thank you very much!

**Comment by fleexo** [comment]
@FIorian haven't found time to do it. So it took some time.
But it is available in the newest version!
